// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Engineering_Gruppenprojekt.Data;

#nullable disable

namespace Web_Engineering_Gruppenprojekt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619192419_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlideFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlidePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterNumber = 1,
                            CourseId = 1,
                            Title = "Grundlagen der Sortieralgorithmen"
                        },
                        new
                        {
                            Id = 2,
                            ChapterNumber = 2,
                            CourseId = 1,
                            Title = "Graphenalgorithmen"
                        },
                        new
                        {
                            Id = 3,
                            ChapterNumber = 1,
                            CourseId = 2,
                            Title = "Neuronale Netze"
                        },
                        new
                        {
                            Id = 4,
                            ChapterNumber = 2,
                            CourseId = 2,
                            Title = "Entscheidungsbäume"
                        });
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LecturerName = "Prof. Dr. Müller",
                            Level = 0,
                            Title = "Algorithmen und Datenstrukturen"
                        },
                        new
                        {
                            Id = 2,
                            LecturerName = "Prof. Dr. Schmidt",
                            Level = 1,
                            Title = "Maschinelles Lernen"
                        });
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.ExamQuestion", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExamId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.MCAnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText = "O(n²)",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerText = "O(n log n)",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnswerText = "O(n)",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            AnswerText = "O(log n)",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            AnswerText = "BubbleSort",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            AnswerText = "MergeSort",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            AnswerText = "InsertionSort",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            AnswerText = "SelectionSort",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            AnswerText = "Den kürzesten Weg in einem gewichteten Graphen",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            AnswerText = "Die Tiefensuche in einem Graphen",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 11,
                            AnswerText = "Das Einfärben von Graphen",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 12,
                            AnswerText = "Den maximalen Fluss in einem Netzwerk",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 13,
                            AnswerText = "Ein Graph ohne Zyklen",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 14,
                            AnswerText = "Ein Graph mit genau einem Knoten",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 15,
                            AnswerText = "Ein vollständig verbundener Graph",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 16,
                            AnswerText = "Ein Graph mit negativen Kanten",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 17,
                            AnswerText = "Eine Funktion, die die Ausgabe eines Neurons bestimmt",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 18,
                            AnswerText = "Eine Methode zur Initialisierung der Gewichte",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 19,
                            AnswerText = "Ein Algorithmus zum Training des Netzes",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 20,
                            AnswerText = "Eine Schicht im neuronalen Netz",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 21,
                            AnswerText = "Das Modell passt sich zu stark an die Trainingsdaten an",
                            IsCorrect = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 22,
                            AnswerText = "Das Modell ist zu einfach für die Daten",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 23,
                            AnswerText = "Die Trainingsdaten enthalten Fehler",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 24,
                            AnswerText = "Das Modell hat zu wenige Parameter",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 25,
                            AnswerText = "Ein Maß für die Unreinheit eines Knotens",
                            IsCorrect = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 26,
                            AnswerText = "Ein Maß für die Tiefe des Baums",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 27,
                            AnswerText = "Die Anzahl der Blätter im Baum",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 28,
                            AnswerText = "Die Genauigkeit des Modells",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 29,
                            AnswerText = "Um Overfitting zu reduzieren",
                            IsCorrect = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 30,
                            AnswerText = "Um die Trainingsgeschwindigkeit zu erhöhen",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 31,
                            AnswerText = "Um mehr Daten zu verarbeiten",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 32,
                            AnswerText = "Um die Genauigkeit auf Trainingsdaten zu steigern",
                            IsCorrect = false,
                            QuestionId = 8
                        });
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.MCQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterId = 1,
                            QuestionText = "Was ist die durchschnittliche Zeitkomplexität von QuickSort?"
                        },
                        new
                        {
                            Id = 2,
                            ChapterId = 1,
                            QuestionText = "Welcher Algorithmus verwendet das Divide-and-Conquer-Prinzip?"
                        },
                        new
                        {
                            Id = 3,
                            ChapterId = 2,
                            QuestionText = "Was beschreibt der Dijkstra-Algorithmus?"
                        },
                        new
                        {
                            Id = 4,
                            ChapterId = 2,
                            QuestionText = "Was ist ein azyklischer Graph?"
                        },
                        new
                        {
                            Id = 5,
                            ChapterId = 3,
                            QuestionText = "Was ist eine Aktivierungsfunktion in neuronalen Netzen?"
                        },
                        new
                        {
                            Id = 6,
                            ChapterId = 3,
                            QuestionText = "Was beschreibt Overfitting beim maschinellen Lernen?"
                        },
                        new
                        {
                            Id = 7,
                            ChapterId = 4,
                            QuestionText = "Was ist der Gini-Index bei Entscheidungsbäumen?"
                        },
                        new
                        {
                            Id = 8,
                            ChapterId = 4,
                            QuestionText = "Wann sollte man einen Entscheidungsbaum beschneiden (Pruning)?"
                        });
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.Chapter", b =>
                {
                    b.HasOne("Web_Engineering_Gruppenprojekt.Models.Course", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.Exam", b =>
                {
                    b.HasOne("Web_Engineering_Gruppenprojekt.Models.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.ExamQuestion", b =>
                {
                    b.HasOne("Web_Engineering_Gruppenprojekt.Models.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Engineering_Gruppenprojekt.Models.MCQuestion", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.MCAnswerOption", b =>
                {
                    b.HasOne("Web_Engineering_Gruppenprojekt.Models.MCQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.MCQuestion", b =>
                {
                    b.HasOne("Web_Engineering_Gruppenprojekt.Models.Chapter", "Chapter")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.Chapter", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.Course", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.Exam", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("Web_Engineering_Gruppenprojekt.Models.MCQuestion", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
